// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protos/job.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseResumeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResumeFileContent []byte                 `protobuf:"bytes,1,opt,name=resume_file_content,json=resumeFileContent,proto3" json:"resume_file_content,omitempty"`
	FileName          string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ParseResumeRequest) Reset() {
	*x = ParseResumeRequest{}
	mi := &file_protos_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResumeRequest) ProtoMessage() {}

func (x *ParseResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResumeRequest.ProtoReflect.Descriptor instead.
func (*ParseResumeRequest) Descriptor() ([]byte, []int) {
	return file_protos_job_proto_rawDescGZIP(), []int{0}
}

func (x *ParseResumeRequest) GetResumeFileContent() []byte {
	if x != nil {
		return x.ResumeFileContent
	}
	return nil
}

func (x *ParseResumeRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type ParseResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobTitles     []string               `protobuf:"bytes,1,rep,name=job_titles,json=jobTitles,proto3" json:"job_titles,omitempty"`
	Skills        []string               `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	Experience    int32                  `protobuf:"varint,3,opt,name=experience,proto3" json:"experience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResumeResponse) Reset() {
	*x = ParseResumeResponse{}
	mi := &file_protos_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResumeResponse) ProtoMessage() {}

func (x *ParseResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResumeResponse.ProtoReflect.Descriptor instead.
func (*ParseResumeResponse) Descriptor() ([]byte, []int) {
	return file_protos_job_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResumeResponse) GetJobTitles() []string {
	if x != nil {
		return x.JobTitles
	}
	return nil
}

func (x *ParseResumeResponse) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ParseResumeResponse) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

type CalculateRelevancyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResumeSkills     []string               `protobuf:"bytes,1,rep,name=resume_skills,json=resumeSkills,proto3" json:"resume_skills,omitempty"`
	ResumeExperience string                 `protobuf:"bytes,2,opt,name=resume_experience,json=resumeExperience,proto3" json:"resume_experience,omitempty"`
	JobDescription   string                 `protobuf:"bytes,3,opt,name=job_description,json=jobDescription,proto3" json:"job_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CalculateRelevancyRequest) Reset() {
	*x = CalculateRelevancyRequest{}
	mi := &file_protos_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRelevancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRelevancyRequest) ProtoMessage() {}

func (x *CalculateRelevancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRelevancyRequest.ProtoReflect.Descriptor instead.
func (*CalculateRelevancyRequest) Descriptor() ([]byte, []int) {
	return file_protos_job_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateRelevancyRequest) GetResumeSkills() []string {
	if x != nil {
		return x.ResumeSkills
	}
	return nil
}

func (x *CalculateRelevancyRequest) GetResumeExperience() string {
	if x != nil {
		return x.ResumeExperience
	}
	return ""
}

func (x *CalculateRelevancyRequest) GetJobDescription() string {
	if x != nil {
		return x.JobDescription
	}
	return ""
}

type CalculateRelevancyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RelevancyScore float64                `protobuf:"fixed64,1,opt,name=relevancy_score,json=relevancyScore,proto3" json:"relevancy_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CalculateRelevancyResponse) Reset() {
	*x = CalculateRelevancyResponse{}
	mi := &file_protos_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRelevancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRelevancyResponse) ProtoMessage() {}

func (x *CalculateRelevancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRelevancyResponse.ProtoReflect.Descriptor instead.
func (*CalculateRelevancyResponse) Descriptor() ([]byte, []int) {
	return file_protos_job_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateRelevancyResponse) GetRelevancyScore() float64 {
	if x != nil {
		return x.RelevancyScore
	}
	return 0
}

var File_protos_job_proto protoreflect.FileDescriptor

const file_protos_job_proto_rawDesc = "" +
	"\n" +
	"\x10protos/job.proto\x12\x03job\"a\n" +
	"\x12ParseResumeRequest\x12.\n" +
	"\x13resume_file_content\x18\x01 \x01(\fR\x11resumeFileContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"l\n" +
	"\x13ParseResumeResponse\x12\x1d\n" +
	"\n" +
	"job_titles\x18\x01 \x03(\tR\tjobTitles\x12\x16\n" +
	"\x06skills\x18\x02 \x03(\tR\x06skills\x12\x1e\n" +
	"\n" +
	"experience\x18\x03 \x01(\x05R\n" +
	"experience\"\x96\x01\n" +
	"\x19CalculateRelevancyRequest\x12#\n" +
	"\rresume_skills\x18\x01 \x03(\tR\fresumeSkills\x12+\n" +
	"\x11resume_experience\x18\x02 \x01(\tR\x10resumeExperience\x12'\n" +
	"\x0fjob_description\x18\x03 \x01(\tR\x0ejobDescription\"E\n" +
	"\x1aCalculateRelevancyResponse\x12'\n" +
	"\x0frelevancy_score\x18\x01 \x01(\x01R\x0erelevancyScore2\xa9\x01\n" +
	"\n" +
	"JobService\x12B\n" +
	"\vParseResume\x12\x17.job.ParseResumeRequest\x1a\x18.job.ParseResumeResponse\"\x00\x12W\n" +
	"\x12CalculateRelevancy\x12\x1e.job.CalculateRelevancyRequest\x1a\x1f.job.CalculateRelevancyResponse\"\x00B\x11Z\x0f./protos;protosb\x06proto3"

var (
	file_protos_job_proto_rawDescOnce sync.Once
	file_protos_job_proto_rawDescData []byte
)

func file_protos_job_proto_rawDescGZIP() []byte {
	file_protos_job_proto_rawDescOnce.Do(func() {
		file_protos_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_job_proto_rawDesc), len(file_protos_job_proto_rawDesc)))
	})
	return file_protos_job_proto_rawDescData
}

var file_protos_job_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_job_proto_goTypes = []any{
	(*ParseResumeRequest)(nil),         // 0: job.ParseResumeRequest
	(*ParseResumeResponse)(nil),        // 1: job.ParseResumeResponse
	(*CalculateRelevancyRequest)(nil),  // 2: job.CalculateRelevancyRequest
	(*CalculateRelevancyResponse)(nil), // 3: job.CalculateRelevancyResponse
}
var file_protos_job_proto_depIdxs = []int32{
	0, // 0: job.JobService.ParseResume:input_type -> job.ParseResumeRequest
	2, // 1: job.JobService.CalculateRelevancy:input_type -> job.CalculateRelevancyRequest
	1, // 2: job.JobService.ParseResume:output_type -> job.ParseResumeResponse
	3, // 3: job.JobService.CalculateRelevancy:output_type -> job.CalculateRelevancyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_job_proto_init() }
func file_protos_job_proto_init() {
	if File_protos_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_job_proto_rawDesc), len(file_protos_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_job_proto_goTypes,
		DependencyIndexes: file_protos_job_proto_depIdxs,
		MessageInfos:      file_protos_job_proto_msgTypes,
	}.Build()
	File_protos_job_proto = out.File
	file_protos_job_proto_goTypes = nil
	file_protos_job_proto_depIdxs = nil
}
