# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: job.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'job.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tjob.proto\x12\x03job\"D\n\x12ParseResumeRequest\x12\x1b\n\x13resume_file_content\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\"M\n\x13ParseResumeResponse\x12\x12\n\njob_titles\x18\x01 \x03(\t\x12\x0e\n\x06skills\x18\x02 \x03(\t\x12\x12\n\nexperience\x18\x03 \x01(\x05\"f\n\x19\x43\x61lculateRelevancyRequest\x12\x15\n\rresume_skills\x18\x01 \x03(\t\x12\x19\n\x11resume_experience\x18\x02 \x01(\t\x12\x17\n\x0fjob_description\x18\x03 \x01(\t\"5\n\x1a\x43\x61lculateRelevancyResponse\x12\x17\n\x0frelevancy_score\x18\x01 \x01(\x01\x32\xa9\x01\n\nJobService\x12\x42\n\x0bParseResume\x12\x17.job.ParseResumeRequest\x1a\x18.job.ParseResumeResponse\"\x00\x12W\n\x12\x43\x61lculateRelevancy\x12\x1e.job.CalculateRelevancyRequest\x1a\x1f.job.CalculateRelevancyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARSERESUMEREQUEST']._serialized_start=18
  _globals['_PARSERESUMEREQUEST']._serialized_end=86
  _globals['_PARSERESUMERESPONSE']._serialized_start=88
  _globals['_PARSERESUMERESPONSE']._serialized_end=165
  _globals['_CALCULATERELEVANCYREQUEST']._serialized_start=167
  _globals['_CALCULATERELEVANCYREQUEST']._serialized_end=269
  _globals['_CALCULATERELEVANCYRESPONSE']._serialized_start=271
  _globals['_CALCULATERELEVANCYRESPONSE']._serialized_end=324
  _globals['_JOBSERVICE']._serialized_start=327
  _globals['_JOBSERVICE']._serialized_end=496
# @@protoc_insertion_point(module_scope)
